#!/usr/bin/env python3
"""Fit a postmarketOS Android boot v0 image into the MediaPad 8 MiB boot partition.

The MediaPad 10 FHD boot partition is exactly 8 MiB.  Recompressing the pmOS
initramfs with XZ preset 9 + CRC32 is necessary for Linux 4.9, but newer/larger
kernels can still push boot.img over the partition limit.

For this device the installed root filesystem is ext4, so with
--slim-ext4-initramfs we remove only filesystem-repair utilities that are not
needed during early boot (btrfs/f2fs/xfs) before recompressing.  The pruning is
performed directly on the CPIO newc stream: all retained entries are copied
byte-for-byte, preserving their metadata, modes, symlinks and ordering.
"""

from __future__ import annotations

import argparse
import hashlib
import lzma
import struct
from pathlib import Path

ANDROID_MAGIC = b"ANDROID!"
ID_OFFSET = 576
ID_SIZE = 32
RAMDISK_SIZE_OFFSET = 16
CPIO_NEWC_MAGICS = (b"070701", b"070702")

# This exact set was tested on the S10 ext4 postmarketOS initramfs.  None of
# these files is needed to locate/mount /dev/mmcblk0p22 as ext4 or switch_root.
EXT4_SLIM_PATHS = {
    "usr/bin/btrfs",
    "usr/bin/fsck.f2fs",
    "usr/bin/resize.f2fs",
    "usr/bin/fsck.xfs",
    "usr/bin/xfs_growfs",
    "usr/bin/xfs_repair",
    "usr/lib/libf2fs.so.10",
    "usr/lib/libf2fs.so.10.0.0",
}


def align(value: int, boundary: int) -> int:
    return (value + boundary - 1) // boundary * boundary


def normalize_cpio_name(name: str) -> str:
    while name.startswith("./"):
        name = name[2:]
    return name.lstrip("/")


def strip_newc_entries(raw: bytes, remove_paths: set[str]) -> tuple[bytes, list[str]]:
    """Remove exact paths from one CPIO newc archive without unpacking it.

    Every retained record is copied verbatim.  CPIO newc records are 4-byte
    aligned, so removing complete records keeps the resulting archive valid.
    """

    pos = 0
    out = bytearray()
    removed: list[str] = []

    while True:
        if pos + 110 > len(raw):
            raise ValueError(f"truncated CPIO header at offset {pos}")

        magic = raw[pos : pos + 6]
        if magic not in CPIO_NEWC_MAGICS:
            raise ValueError(
                f"unsupported initramfs CPIO magic {magic!r} at offset {pos}; "
                "expected newc/crc"
            )

        header = raw[pos : pos + 110]
        try:
            fields = [
                int(header[6 + i * 8 : 14 + i * 8], 16)
                for i in range(13)
            ]
        except ValueError as exc:
            raise ValueError(f"invalid CPIO header at offset {pos}") from exc

        filesize = fields[6]
        namesize = fields[11]
        if namesize < 1:
            raise ValueError(f"invalid CPIO namesize {namesize} at offset {pos}")

        name_start = pos + 110
        name_end = name_start + namesize
        if name_end > len(raw):
            raise ValueError(f"truncated CPIO filename at offset {pos}")

        name_bytes = raw[name_start:name_end]
        if name_bytes[-1:] != b"\0":
            raise ValueError(f"CPIO filename is not NUL-terminated at offset {pos}")

        name = name_bytes[:-1].decode("utf-8", errors="surrogateescape")
        data_start = align(name_end, 4)
        data_end = data_start + filesize
        next_pos = align(data_end, 4)
        if next_pos > len(raw):
            raise ValueError(f"truncated CPIO data for {name!r}")

        normalized = normalize_cpio_name(name)
        if normalized == "TRAILER!!!":
            out.extend(raw[pos:next_pos])
            # Preserve any end padding exactly as generated by pmbootstrap.
            out.extend(raw[next_pos:])
            break

        if normalized in remove_paths:
            removed.append(normalized)
        else:
            out.extend(raw[pos:next_pos])

        pos = next_pos

    return bytes(out), removed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument(
        "--slim-ext4-initramfs",
        action="store_true",
        help="drop tested btrfs/f2fs/xfs early-boot tools; rootfs must be ext4",
    )
    args = parser.parse_args()

    image = args.input.read_bytes()
    if image[:8] != ANDROID_MAGIC:
        raise SystemExit("not an Android boot image")

    (
        kernel_size,
        kernel_addr,
        ramdisk_size,
        ramdisk_addr,
        second_size,
        second_addr,
        tags_addr,
        page_size,
        dt_size,
        unused,
    ) = struct.unpack_from("<10I", image, 8)

    if page_size <= 0 or page_size > 65536:
        raise SystemExit(f"invalid page size: {page_size}")
    if second_size != 0:
        raise SystemExit("unexpected second stage; refusing to rewrite")
    if dt_size != 0:
        raise SystemExit("unexpected boot header DT payload; DTB should be appended to zImage")

    kernel_offset = page_size
    kernel = image[kernel_offset : kernel_offset + kernel_size]
    ramdisk_offset = align(kernel_offset + kernel_size, page_size)
    ramdisk = image[ramdisk_offset : ramdisk_offset + ramdisk_size]

    if len(kernel) != kernel_size or len(ramdisk) != ramdisk_size:
        raise SystemExit("boot image is truncated")

    try:
        raw_initramfs = lzma.decompress(ramdisk)
    except lzma.LZMAError as exc:
        raise SystemExit(f"ramdisk is not an XZ/LZMA stream: {exc}") from exc

    original_raw_size = len(raw_initramfs)
    removed: list[str] = []
    if args.slim_ext4_initramfs:
        try:
            raw_initramfs, removed = strip_newc_entries(
                raw_initramfs, EXT4_SLIM_PATHS
            )
        except ValueError as exc:
            raise SystemExit(f"cannot slim initramfs safely: {exc}") from exc

        print(f"slim_removed_count={len(removed)}")
        for path in removed:
            print(f"slim_removed={path}")
        print(f"old_initramfs_raw_size={original_raw_size}")
        print(f"new_initramfs_raw_size={len(raw_initramfs)}")
        print(f"initramfs_raw_saved={original_raw_size - len(raw_initramfs)}")

    # Linux 4.9's early XZ decoder in this kernel accepts CRC32, not CRC64.
    recompressed = lzma.compress(
        raw_initramfs,
        format=lzma.FORMAT_XZ,
        check=lzma.CHECK_CRC32,
        preset=9,
    )

    header = bytearray(image[:page_size])
    struct.pack_into("<I", header, RAMDISK_SIZE_OFFSET, len(recompressed))
    header[ID_OFFSET : ID_OFFSET + ID_SIZE] = b"\0" * ID_SIZE

    # Android boot image v0 ID: SHA1(kernel + kernel_size + ramdisk +
    # ramdisk_size + second + second_size). The S10 image has no second stage.
    digest = hashlib.sha1()
    digest.update(kernel)
    digest.update(struct.pack("<I", kernel_size))
    digest.update(recompressed)
    digest.update(struct.pack("<I", len(recompressed)))
    digest.update(struct.pack("<I", 0))
    header[ID_OFFSET : ID_OFFSET + 20] = digest.digest()

    output = bytearray(header)
    output.extend(kernel)
    output.extend(b"\0" * (align(kernel_size, page_size) - kernel_size))
    output.extend(recompressed)
    output.extend(b"\0" * (align(len(recompressed), page_size) - len(recompressed)))

    # Verify that compression did not alter the final (possibly slimmed) CPIO.
    check_offset = align(page_size + kernel_size, page_size)
    check_ramdisk = bytes(output[check_offset : check_offset + len(recompressed)])
    if lzma.decompress(check_ramdisk) != raw_initramfs:
        raise SystemExit("repacked initramfs verification failed")

    # If slimming was requested, parse the result once more and prove none of
    # the requested paths survived.  This catches malformed/tricky CPIO names.
    if args.slim_ext4_initramfs:
        try:
            _, still_present = strip_newc_entries(raw_initramfs, EXT4_SLIM_PATHS)
        except ValueError as exc:
            raise SystemExit(f"slimmed initramfs validation failed: {exc}") from exc
        if still_present:
            raise SystemExit(
                "slimmed initramfs still contains removable paths: "
                + ", ".join(still_present)
            )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(output)

    print(f"page_size={page_size}")
    print(f"kernel_size={kernel_size}")
    print(f"old_ramdisk_size={ramdisk_size}")
    print(f"new_ramdisk_size={len(recompressed)}")
    print("xz_check=crc32")
    print(f"old_boot_size={len(image)}")
    print(f"new_boot_size={len(output)}")
    print(f"sha256={hashlib.sha256(output).hexdigest()}")

    if args.limit and len(output) > args.limit:
        raise SystemExit(
            f"repacked boot.img is still too large: {len(output)} > {args.limit} bytes"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
